version: '3.8'

services:
  php:
    build: './php'
    volumes:
      - ./app:/app:cached
    working_dir: /app
    depends_on:
      - mysql
    links:
      - mysql

  nginx:
    image: nginx:1.25-alpine
    ports:
      - '127.0.0.1:${NGINX_PUBLIC_PORT}:80'
    volumes:
      - ./app:/app:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    links:
      - php

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - '127.0.0.1:${MYSQL_PUBLIC_PORT}:3306'
    volumes:
      - mysql_data:/var/lib/mysql:rw

volumes:
  mysql_data: {}
